k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  apiServerTimeout: 15s
  maxConnRetry: 5
  readOnly: false
  defaultView: ""
  noExitOnCtrlC: true
  portForwardAddress: localhost
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    reactive: false
    noIcons: false
    skin: gruvbox-material-dark-soft
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: debian:stable-slim
    namespace: default
    limits:
      cpu: 200m
      memory: 200Mi
    tty: true
  imageScans:
    enable: false
    exclusions:
      namespaces:
        - kube-system
        - fred
      labels:
        k8s-app:
          - kindnet
          - bozo
        env:
          - dev
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: -1
    fullScreen: true
    textWrap: false
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 85
      warn: 75
